# Generated by Django 3.2.9 on 2021-12-22 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('maker', models.CharField(max_length=100)),
                ('number_of_players', models.IntegerField()),
                ('skill_level', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='levelupapi.category')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='levelupapi.gamer')),
            ],
        ),
    ]
