# Generated by Django 3.2.9 on 2022-01-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
